### ISSUE TITLE
What is WaffleDB

### ISSUE THREAD

**Issue by TortleWortle** [PancakeDB/PancakeDB#4]
What exactly is WaffleDB (going to be).

What are some of the core concepts and problems/issues it’s solving?

**Comment by LewisTehMinerz** [comment]
>WaffleDB

PancakeDB, you mean?

Also, it's just going to be a fun project. As it suggests, it's a database system and it's not really got anything set in concrete yet. It will just be developed and features will be added when needed. It's too early in the development cycle to say what issues it will solve.

**Comment by TortleWortle** [comment]
Yeah I meant PancakeDB, got confused by database.js#53

**Comment by LewisTehMinerz** [comment]
Oh, whoopsies! Thanks for letting me know about that. Need to go push a commit, be back in a few.
